//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PchK22CNT3Lesson10Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PchAccount
    {
        public string PchUserName { get; set; }
        public string PchPassword { get; set; }
        public string PchFullName { get; set; }
        public string PchEmail { get; set; }
        public string PchPhone { get; set; }
        public Nullable<bool> PchActive { get; set; }
        public int PchID { get; set; }
    }
}
